//---
//About this .cpp code :
//
//Started from the template code generated by Visual Studio (Project type : C++ Win32 desktop APP).
//  * Removed unnecessary resources (menu, accelerator, icon, about-box, etc) and codes used them.
//	* Changed Window's properties (: MyRegisterClass() and InitInstance() ).
//	* etc.
//---

#include "framework.h"
//#include "resource.h"
#include <windowsx.h>
#include <numbers>

//for DwmSetWindowAttribute()
#include <dwmapi.h>
#pragma comment(lib, "dwmapi.lib")

//
#include "Code/Test.h"

namespace
{
	//Set Window client area size to W*H
	bool SetWindowClientAreaSize( int W, int H, HWND hWnd )
	{
		//for Loop : Try several times.
		//	However, here, maybe achieved via 1st SetWindowPos() call, because the window has no menu-bar, etc.
		//	(excepting very small W)
		for( int i=0; i<2; ++i )
		{
			RECT R;
			::GetClientRect( hWnd, &R );
			int dx = W - R.right;
			int dy = H - R.bottom;
			if( dx==0 && dy==0 )return true;

			::GetWindowRect( hWnd, &R );
			::SetWindowPos( hWnd, NULL, 0,0, (R.right-R.left)+dx, (R.bottom-R.top)+dy, SWP_NOMOVE|SWP_NOZORDER );
		}
		return false;
	}
}

HINSTANCE hInst;
constexpr WCHAR szWindowClass[] = L"WndClassName";

ATOM                MyRegisterClass( HINSTANCE hInstance );
HWND                InitInstance( HINSTANCE, int );
LRESULT CALLBACK    WndProc( HWND, UINT, WPARAM, LPARAM );

int APIENTRY wWinMain(
	_In_ HINSTANCE hInstance,
	_In_opt_ HINSTANCE hPrevInstance,
	_In_ LPWSTR    lpCmdLine,
	_In_ int       nCmdShow
)
{
	UNREFERENCED_PARAMETER( hPrevInstance );
	UNREFERENCED_PARAMETER( lpCmdLine );

	MyRegisterClass( hInstance );
	HWND hWnd = InitInstance( hInstance, nCmdShow );
	if( hWnd==NULL )return FALSE;
	SetWindowClientAreaSize( IMG_W, IMG_H, hWnd );

	//
	MSG msg;
	while( GetMessage( &msg, nullptr, 0, 0 ) )
	{
		TranslateMessage( &msg );
		DispatchMessage( &msg );
	}

	return (int)msg.wParam;
}

ATOM MyRegisterClass( HINSTANCE hInstance )
{
	WNDCLASSEXW wcex = { 0 };
	wcex.cbSize = sizeof( WNDCLASSEX );
	wcex.style = CS_HREDRAW | CS_VREDRAW;
	wcex.lpfnWndProc = WndProc;
	wcex.cbClsExtra = 0;
	wcex.cbWndExtra = 0;
	wcex.hInstance = hInstance;
	wcex.hCursor = LoadCursor( nullptr, IDC_ARROW );
	wcex.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
	wcex.lpszMenuName = 0;
	wcex.lpszClassName = szWindowClass;
	return RegisterClassExW( &wcex );
}

//Returns the handle of created window, or NULL on failure.
HWND InitInstance( HINSTANCE hInstance, int nCmdShow )
{
	hInst = hInstance;

	HWND hWnd = CreateWindowW(
		szWindowClass,
		L"Pseudo 3D Maze Rendering Test",	//caption
		WS_OVERLAPPED | WS_SYSMENU,	//No sizing border
		100, 100,	//position : This value has no particular meaning.
		320, 240,	//size : This value has no particular meaning, will be changed later.
		nullptr,	//No Parent
		nullptr,	//Menu : depend on window_class
		hInstance,
		nullptr
	);
	if( hWnd )
	{
		ShowWindow( hWnd, nCmdShow );
		UpdateWindow( hWnd );
	}
	return hWnd;
}

LRESULT CALLBACK WndProc( HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam )
{
	//Data for Test
	static Vec2d CameraPos{ 0.5, 0.5 };	//(0.5, 0.5) = center of most north-west square
	static double CameraDir = 0;	//[rad]
	static HBITMAP hCanvasBmp = NULL;

	switch( message )
	{
	case WM_CREATE:
		{
			//Stop rounding window corner.
			//	In default, current Windows round window corners.
			//	This undesired default behavior cuts bottom corner parts of client area. Terrible. Horrible.
			//	This behavior is inconvenient here because I need to check entire image rendered by my code.
			//	So, I googled and found this way.
			DWM_WINDOW_CORNER_PREFERENCE Attr = DWMWCP_DONOTROUND;
			DwmSetWindowAttribute( hWnd, DWMWA_WINDOW_CORNER_PREFERENCE, &Attr, sizeof(Attr) );
		}
		break;
	case WM_KEYDOWN:
		{
			constexpr double MoveAmount = 0.1;
			constexpr double YawingAmount = 0.05;
			constexpr double PI2 = 2 * std::numbers::pi;
			bool ShouldRedraw = false;
			switch( wParam )
			{
			case VK_NUMPAD8:	//Go forward
				CameraPos += MoveAmount * Vec2d{ std::cos(CameraDir), std::sin(CameraDir) };
				ShouldRedraw = true;
				break;
			case VK_NUMPAD2:	//Go backward
				CameraPos -= MoveAmount * Vec2d{ std::cos(CameraDir), std::sin(CameraDir) };
				ShouldRedraw = true;
				break;
			case VK_NUMPAD9:	//Move right
				CameraPos += MoveAmount * Vec2d{ -std::sin(CameraDir), std::cos(CameraDir) };
				ShouldRedraw = true;
				break;
			case VK_NUMPAD7:	//Move left
				CameraPos -= MoveAmount * Vec2d{ -std::sin(CameraDir), std::cos(CameraDir) };
				ShouldRedraw = true;
				break;
			case VK_NUMPAD4:	//Yawing left
				CameraDir -= YawingAmount;
				if( CameraDir < 0.9 )CameraDir += PI2;
				ShouldRedraw = true;
				break;
			case VK_NUMPAD6:	//Yawing right
				CameraDir += YawingAmount;
				if( CameraDir > PI2)CameraDir -= PI2;
				ShouldRedraw = true;
				break;
			default:
				break;
			}
			if( ShouldRedraw )
			{	InvalidateRect( hWnd, NULL, FALSE );	}
		}
		break;
	case WM_PAINT:
		{
			PAINTSTRUCT ps;
			HDC hdc = BeginPaint( hWnd, &ps );

			if( hCanvasBmp == NULL )	//when 1st time
			{	hCanvasBmp = CreateCompatibleBitmap( hdc, IMG_W, IMG_H );	}

			if( hCanvasBmp != NULL )
			{
				if( HDC hMemDC = CreateCompatibleDC( hdc );	hMemDC!=NULL )
				{
					HBITMAP OldBmp = SelectBitmap( hMemDC, hCanvasBmp );
					Test02_Render( CameraPos, CameraDir, hMemDC );
					BitBlt( hdc, 0,0, IMG_W, IMG_H, hMemDC, 0,0, SRCCOPY );
					SelectBitmap( hMemDC, OldBmp );
					DeleteDC( hMemDC );
				}
			}
			EndPaint( hWnd, &ps );
		}
		break;
	case WM_DESTROY:
		{
			if( hCanvasBmp != NULL )
			{	DeleteObject( hCanvasBmp );	hCanvasBmp=NULL;	}

			PostQuitMessage( 0 );
		}
		break;
	default:
		return DefWindowProc( hWnd, message, wParam, lParam );
	}
	return 0;
}
